### PR TITLE
Notes for 2024-07-03-PAS-call

### PR DESCRIPTION
**Pull request by akshaypundle**

### CODE REVIEW

**Comment by dmdabbs** [comment]
The meeting notes say

>Alex: Will send link to presentation after 

Would like to review the slides; was unable to attend. Thanks.

**Comment by lx3-g** [comment]
https://github.com/WICG/protected-auction-services-discussion/blob/main/resources/wicg-hybrid-protocol-proposal-2024-07-03.pdf

**Comment by dmdabbs** [comment]
@lx3-g I get

Error rendering embedded code
Invalid PDF

**Comment by dmdabbs** [comment]
Faulty browser. Nevermind. 
Thanks again for the pointer, Alex.

**Pull request merged**
